export const CartActions = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  REDUCE_QUANTITY: "REDUCE_QUANTITY",
  CHECKOUT_CART: "CHECKOUT_CART",
};

export const SearchBookActions = {
  STORE_SEARCHED_BOOKS: "STORE_SEARCHED_BOOKS",
  CLEAR_SEARCHED_BOOKS: "CLEAR_SEARCHED_BOOKS",
  FETCHING_SEARCHED_BOOKS: "FETCHING_SEARCHED_BOOKS",
};
